// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5pBVMi1kn92qbrZNq1Iv7w6T_SbXh9Gc',
    appId: '1:796361877332:web:aba6f1a58fabd7e3a28ac1',
    messagingSenderId: '796361877332',
    projectId: 'mangalore-guide-zyn',
    authDomain: 'mangalore-guide-zyn.firebaseapp.com',
    storageBucket: 'mangalore-guide-zyn.firebasestorage.app',
    measurementId: 'G-6RL88FSWTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtIvDA-zF47Wpfrli8SyquZdtmfh_YeM',
    appId: '1:796361877332:android:3c12de1baf8a5f8ea28ac1',
    messagingSenderId: '796361877332',
    projectId: 'mangalore-guide-zyn',
    storageBucket: 'mangalore-guide-zyn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKa_YfmII96Zqn5XBmUSoy8q9PBTSUsnI',
    appId: '1:796361877332:ios:7daa8ab5cea03847a28ac1',
    messagingSenderId: '796361877332',
    projectId: 'mangalore-guide-zyn',
    storageBucket: 'mangalore-guide-zyn.firebasestorage.app',
    iosBundleId: 'com.example.localGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKa_YfmII96Zqn5XBmUSoy8q9PBTSUsnI',
    appId: '1:796361877332:ios:7daa8ab5cea03847a28ac1',
    messagingSenderId: '796361877332',
    projectId: 'mangalore-guide-zyn',
    storageBucket: 'mangalore-guide-zyn.firebasestorage.app',
    iosBundleId: 'com.example.localGuideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5pBVMi1kn92qbrZNq1Iv7w6T_SbXh9Gc',
    appId: '1:796361877332:web:92dc304102c7ba48a28ac1',
    messagingSenderId: '796361877332',
    projectId: 'mangalore-guide-zyn',
    authDomain: 'mangalore-guide-zyn.firebaseapp.com',
    storageBucket: 'mangalore-guide-zyn.firebasestorage.app',
    measurementId: 'G-V4Q6TJV8PH',
  );
}
